

<div class="row clearfix">
<div class="col-md-4 column" style='margin-top:100px;'>
<div id="form" style="display: block;">
    <form id="form1" action="<?php echo $this->baseUrl().$this->action ?>" method="post">
        <?=$this->form->name ?>
        <?=$this->form->body ?>
        <?=$this->form->forum_id ?>
        <input type="hidden" value="<?= $this->threadId ?>" name="threadId">
        <?php if($this->action == "/thread/edit"){
            echo $this->form->edit;
        }else{
            echo $this->form->add;
        } 
        
        //echo $this->array;
        ?>
 </form> 
</div>
</div>
</div>    