

<div class="container" style="margin-top: 100px;">
	<div class="row clearfix">
		<div class="col-md-12 column" id="<?= $this->thread_id ?>" class="post" >
                    <div id="thread_title" style='height:30px; padding-left:10px; padding-top:5px; border-radius:3px; background:#3B5999; color:white;'>  </div>
                                             <div id="notify" style="display:none; margin:10px; width:40%; border:1px solid; border-radius:2px; height:30px; padding:5px;"></div>

                    <div id="thread">
                        
                    </div> 
                    
                    <div id="replies">
                        
                        
                    </div>
                    <div id="form" style="display:none">
                     
                        <form action="/ZendProject/public/reply/add" method="post" id="form1">

                        <?=$this->form->body ?>
                        <input type="hidden" value="<?= $this->thread_id ?>" name="threadId">
                        <?=$this->form->add ?>     

                         </form> 
                       
                    </div>
                    
                    </div>
                 
                </div>
</div>
<script>
     var mythread = <?= $this->thread_id?>;
     window.onload= getPost(<?php echo $this->thread_id?>);
     var x;
      
      function getPost(thread_id){
              
       $.getJSON("/ZendProject/public/thread/read/threadId/"+thread_id , function(data,status){
            console.log(data);
         x=data;
         threadDiv = document.getElementById("thread");
         threadDiv.innHTML="";
         titleDiv =document.getElementById("thread_title");
         repliesDiv=document.getElementById("replies");
         repliesDiv.innerHTML="";
         
         titleDiv.innerHTML="Thread : "+data.thread[0].title;   
        
         
         var color= "#B2AFAF";
         
          if(data.thread[0].location == null) data.thread[0].location="";
            if(data.thread[0].image == null) data.thread[0].image="/ZendProject/public/images/default.png";
            
         var body = "<div id='space' style='height:10px; border-radius:2px;'></div><div id='userinfo' style='position:relative; padding:10px;  border-radius:5px; background:"+color+"; color:black'>date : "+data.thread[0].date+"\n\
                   <br><br><img style='display:inline-block; margin-right:20px;' src='"+data.thread[0].image+"' width=100px height=100px>\n\
                    "+data.thread[0].username+"<div id='panel' style='display:none; background:rgba(0,0,0,0.4); color:white; margin-left:220px; position:absolute; top:0px; width:100px;'><ul style='list-style:none;' ><li style='display:inline-block'><i class='glyphicon glyphicon-pencil' title='Edit' onclick=\"opthread('edit');\"></i></li>&nbsp&nbsp<li style='display:inline-block;'><i class='glyphicon glyphicon-trash' title='Delete' onclick=\"opthread('delete);\"></i></li></ul></div><div style='display:inline-block; padding:10px; float:right;'><ul style='list-style:none'>\n\
                    <li>join date : "+data.thread[0].date_joined+"</li>\n\
                    <li>location  : "+data.thread[0].location+"</li>\n\
                    <li>Posts     :  empty for now </li></ul>\n\
                    </div>\n\
                     <div id='title' style='margin-top:5px;'>"+data.thread[0].title+"</div>\n\
                      <hr><div id='body'><br><p>"+data.thread[0].body+"</p></div>\n\
                        <div id='end' style='margin-top:30px;min-height:20px; border-radius:2px; background:#3B5999; color:white;'><a style='color:white; margin-left:700px;' onclick=\"reply("+data.thread[0].id+")\">Reply</a>&nbsp&nbsp&nbsp<a style='color:white;' href=''>Reply with quote</a></div>\n\
                        ";
        
        threadDiv.innerHTML=body;    
          color ="#D2CECE";
          for (var i=0;i< data.replies.length;i++){
              
            var mydiv = document.createElement('div');
            mydiv.className="replyy";
            
            if(data.replies[i].location == null) data.replies[i].location="";
            if(data.replies[i].image == null) data.replies[i].image="/ZendProject/public/images/default.png";
            
            
               var body = "<div id='space' style='height:10px; border-radius:2px;'></div><div id='userinfo' style=' position:relative; padding:10px;  border-radius:5px; background:"+color+"; color:black'>date : "+data.replies[0].date+"\n\
                   <br><br><img style='display:inline-block; margin-right:20px;' src='"+data.replies[i].image+"' width=100px height=100px>\n\
                    "+data.replies[i].username+"<div id='panel' style='display:none; background:rgba(0,0,0,0.4); color:white; margin-left:220px; position:absolute; top:0px; width:100px;'><ul style='list-style:none;' ><li style='display:inline-block'><i class='glyphicon glyphicon-pencil' title='Edit' onclick=\"rpthread("+data.replies[i].id+",'edit');\"></i></li>&nbsp&nbsp<li style='display:inline-block;'><i class='glyphicon glyphicon-trash' title='Delete' onclick=\"rpthread("+data.replies[i].id+",'delete');\"></i></li></ul></div><div style='display:inline-block; padding:10px; float:right;'><ul style='list-style:none'>\n\
                    <li>join date : "+data.replies[i].date_joined+"</li>\n\
                    <li>location  : "+data.replies[i].location+"</li>\n\
                    <li>Posts     :  empty for now </li></ul>\n\
                    </div>\n\
                     <div id='title' style='margin-top:5px;'>RE:"+data.thread[0].title+"</div>\n\
                      <hr><div id='body'><br><p>"+data.replies[i].title+"</p></div>\n\
                        <div id='end' style='margin-top:30px;min-height:20px; border-radius:2px; background:#3B5999; color:white;'><a style='color:white; margin-left:700px;' onclick=\"reply("+data.thread[0].id+")\">Reply</a>&nbsp&nbsp&nbsp<a style='color:white;' href=''>Reply with quote</a></div>";
                        
    
               mydiv.innerHTML=body;
               
             repliesDiv.appendChild(mydiv); 
              
              if(color == "#D2CECE") color="#B2AFAF";
              else color = "#D2CECE";
            
              
              
          }    
          
          
          
          
          
          
          
        });
    }
    
    
    function reply(){
    
    
       var form = document.getElementById("form");
       form.style.display="block";
       form.click()
    
    };
    
    
    function opthread(operation){
     
     if(operation == 'edit'){
         
         
        }
     else{
         
         
         
        }
        
    }
    
    function rpthread(reply_id,operation){
        
       if(operation == 'edit'){
         
         window.location.href="/ZendProject/public/reply/edit/threadId/"+mythread+"/replyId/"+reply_id;
         
        }
     else{
         
         $.get("/ZendProject/public/reply/delete/replyId/"+reply_id,function(data,status){
             
             if(data > 0){
              notification("Reply deleted","#57E964");
                getPost(mythread);
               
            }
            
            else notification("Failed To Delete Reply","#F75D59");
            
             
             
         
            });
        }
    }
        
        
    
    
    
    
     $(document).on({
    mouseenter: function () {
    
    $( '#panel', $( this ) ).css("display","inline-block");
 
     
    
    },
    mouseleave: function () {
         this.style.zIndex="20";
        $('#panel', $( this ) ).css("display","none");
       
   
         
    }
},"#userinfo");


 function notification(message,color){
    
     var notify = document.getElementById("notify");
            notify.style.display="block";
            notify.style.background = color;
            notify.innerHTML=message;
            setTimeout(function(){ notify.style.display="none";},6000);
    
    
    }

 /*$(document).on({
    mouseenter: function () {
    
    $( '#panel', $( this ) ).css("display","inline-block");
 
     
    
    },
    mouseleave: function () {
         this.style.zIndex="20";
        $('#panel', $( this ) ).css("display","none");
       
   
         
    }
},"#thread");
    
  */
    
    
 </script>   