<!DOCTYPE html>
<html lang="en">
    <head>

<?php $url=$this->baseUrl();
        echo "
          
        <script src='$url/js/jquery-2.1.0.min.js' type='text/javascript' language='javascript'></script>
        <meta http-equiv='content-type' content='text/html; charset=UTF-8'> 
        <title>ZendProject</title>
        <meta name='generator' content='Bootply' />
        <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
        <link href='$url/css/bootstrap.min.css' rel='stylesheet'>
	<script src='$url/js/bootstrap.js' type='text/javascript' language='javascript'></script>
        
	<link type='text/css' rel='stylesheet' href='$url/css/style.css' />
            
        ";?>
                 <script type="text/javascript" src="/ZendProject/public/js/jquery.leanModal.min.js" language="javascript"></script>
                 

	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />

        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->










        <!-- CSS code from Bootply.com editor -->
        
        <style type="text/css">
            /* custom template */
html, body {
   height: 100%;
   font-family:verdana,arial,sans-serif;
   color:#555555;
   font-family: sans-serif;
}

.nav {
   font-family:Arial,sans-serif;
   font-size:13px;
}

.cat{
 border-top-right-radius: 10px; 
  border-top-left-radius: 10px; 
 background:#3B5999;
 color:white;
 height:50px;   
    
}

.cat_title{
    
position:relative;
top:10px;
left:20px;
font-size: 150%;
    
    
    
}

.panel-body{
    border:1px grey;
    text-align: center;
    
}

a {
  color:#222222;
}

a:hover {
  text-decoration:none;
}

hr {
  border-color:#dedede;
}

.wrapper, .row {
   height: 100%;
   margin-left:0;
   margin-right:0;
}

.notification{
    
    display:none; margin:10px; width:40%; border:1px solid; border-radius:2px; height:30px; padding:5px;
    
    
}
.wrapper:before, .wrapper:after,
.column:before, .column:after {
    content: "";
    display: table;
}

.wrapper:after,
.column:after {
    clear: both;
}

.column {
    height: 100%;
    overflow: auto;
    *zoom:1;
}

.column .padding {
    padding: 20px;
}

.full{
	padding-top:70px;
}

.box {
  	bottom: 0; /* increase for footer use */
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    background-color:#444444;
  /*
    background-image:url('/assets/example/bg_suburb.jpg');
    background-size:cover;
    background-attachment:fixed;
  */
}

.divider {
	margin-top:32px;
}

.navbar-blue {
    border-width:0;
	background-color:#3B5999;
    color:#ffffff;
    font-family:arial,sans-serif;
    top:0;
    position:fixed;
    width:inherit;
}

.navbar-blue li > a,.navbar-toggle  {
   color:#efefef;
}

.navbar-blue .dropdown-menu li a {color:#2A4888;}
.navbar-blue .dropdown-menu li > a {padding-left:30px;}

.navbar-blue li>a:hover, .navbar-blue li>a:focus, .navbar-blue .open, .navbar-blue .open>a, .navbar-blue .open>a:hover, .navbar-blue .open>a:focus {
   background-color:#2A4888;
   color:#fff;
}

#main {
   background-color:#e9eaed;
   padding-left:0;
   padding-right:0;
}
#main .img-circle {
   margin-top:18px;
   height:70px;
   width:70px;
}

#sidebar {
    padding:0px;
	padding-top:15px;
}

#sidebar, #sidebar a, #sidebar-footer a {
    color:#ffffff;
    background-color:transparent;
	text-shadow:0 0 2px #000000;
    padding-left:5px;
}
#sidebar .nav li>a:hover {
    background-color:#393939;
}

.logo {
  display:block;
  padding:3px;
  background-color:#fff;
  color:#3B5999;
  height:28px;
  width:28px;
  margin:9px;
  margin-right:2px;
  margin-left:15px;
  font-size:20px;
  font-weight:700;
  text-align:center;
  text-decoration:none;
  text-shadow:0 0 1px;
  border-radius:2px;
}
#sidebar-footer {
  background-color:#444;
  position:absolute;
  bottom:5px;
  padding:5px;
}
#footer {
  margin-bottom:20px;
}

/* bootstrap overrides */

h1,h2,h3 {
   font-weight:800;
}

.navbar-toggle, .close {
	outline:0;
}

.navbar-toggle .icon-bar {
	background-color: #fff;
}

.btn-primary,.label-primary,.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus  {
	background-color:#3B5999;
    color:#fffffe;
}
.btn-default {
    color:#666666;
    text-shadow:0 0 1px rgba(0,0,0,.3);
}
.form-control {
	
}

.panel textarea, .well textarea, textarea.form-control
{
   resize: none;
}
  
.badge{
   color:#3B5999;
   background-color:#fff;
}
.badge:hover, .badge-inverse{
   background-color:#3B5999;
   color:#fff;
}
    
.jumbotron {
  background-color:transparent;
}
.label-default {
  background-color:#dddddd;
}
.page-header {
  margin-top: 55px;
  padding-top: 9px;
  border-top:1px solid #eeeeee;
  font-weight:700;
  text-transform:uppercase;
  letter-spacing:2px;
}

.panel-default .panel-heading {
  background-color:#f9fafb;
  color:#555555;
}

.col-sm-9.full {
    width: 100%;
}

.modal-header, .modal-footer {
	background-color:#f2f2f2;
    font-weight:800;
    font-size:12px;
}

.modal-footer i, .well i {
    font-size:20px;
    color:#c0c0c0;
}

.modal-body {
	padding:0px;
}

.modal-body textarea.form-control
{
   resize: none;
   border:0;
   box-shadow:0 0 0;
}

small.text-muted {
  font-family:courier,courier-new,monospace;
}

/* adjust the contents on smaller devices */
@media (max-width: 768px) {

  .column .padding {
    padding: 7px;
  }

  .full{
	padding-top:20px;
  }

  .navbar-blue {
	background-color:#3B5999;
    top:0;
    width:100%;
    position:relative;
  }

}

#modal_trigger label{
    color:black;
}

#editpanel{
    
   display:none; 
}
.dropdown-submenu {
    position: relative;
}

.dropdown-submenu>.dropdown-menu {
    top: 0;
    left: 100%;
    margin-top: -6px;
    margin-left: -1px;
    -webkit-border-radius: 0 6px 6px 6px;
    -moz-border-radius: 0 6px 6px;
    border-radius: 0 6px 6px 6px;
}

.dropdown-submenu:hover>.dropdown-menu {
    display: block;
}

.dropdown-submenu>a:after {
    display: block;
    content: " ";
    float: right;
    width: 0;
    height: 0;
    border-color: transparent;
    border-style: solid;
    border-width: 5px 0 5px 5px;
    border-left-color: #ccc;
    margin-top: 5px;
    margin-right: -10px;
}

.dropdown-submenu:hover>a:after {
    border-left-color: #fff;
}

.dropdown-submenu.pull-left {
    float: none;
}

.dropdown-submenu.pull-left>.dropdown-menu {
    left: -100%;
    margin-left: 10px;
    -webkit-border-radius: 6px 0 6px 6px;
    -moz-border-radius: 6px 0 6px 6px;
    border-radius: 6px 0 6px 6px;
}

/*
 * off canvas sidebar
 * --------------------------------------------------
 */
@media screen and (max-width: 768px) {
  .row-offcanvas {
    position: relative;
    -webkit-transition: all 0.25s ease-out;
    -moz-transition: all 0.25s ease-out;
    transition: all 0.25s ease-out;
  }

  .row-offcanvas-left.active {
    left: 33%;
  }

  .row-offcanvas-left.active .sidebar-offcanvas {
    left: -33%;
    position: absolute;
    top: 0;
    width: 33%;
    margin-left: 5px;
  }

  #sidebar, #sidebar a, #sidebar-footer a {
    padding-left:3px;
  }
}
#darkness {
    background:rgba(0, 0, 0, 0.5);
    display:none;
    height:100%;
    left:0;
    position:absolute;
    top:0;
    width:100%;
    z-index:5;
}
        </style>
    </head>
    
 
    <body  >
        <div id="darkness"></div>
        
        <div class="wrapper">
    <div class="box">
        <div class="row row-offcanvas row-offcanvas-left">
                      
          
            <!-- sidebar -->
        ////////////////////////////////
            <!-- /sidebar -->
          
            <!-- main right col -->
            <div class="column col-sm-12 col-xs-11" id="main">
                
                <!-- top nav -->
              	<div class="navbar navbar-blue navbar-static-top">  
                    <div class="navbar-header">
                      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle</span>
                        <span class="icon-bar"></span>
          				<span class="icon-bar"></span>
          				<span class="icon-bar"></span>
                      </button>
                      <a href="/" class="navbar-brand logo">b</a>
                  	</div>
                  	<nav class="collapse navbar-collapse" role="navigation">
                    <form class="navbar-form navbar-left">
                        <div class="input-group input-group-sm" style="max-width:360px;">
                          <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
                          <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                          </div>
                        </div>
                    </form>
                    <ul class="nav navbar-nav">
                      <li>
                        <a href="#"><i class="glyphicon glyphicon-home"></i> Home</a>
                      </li>
                      <li>
                        <?php $userInfo = new Zend_Session_Namespace('Zend_Auth');  
                    
                        if(isset($userInfo->storage->id)){
                             //reditrect to login popup
                         } 
                      echo "  <a href='$url/thread/add' role='button' data-toggle='modal'><i class='glyphicon glyphicon-plus'></i> Post</a>";
                      ?>
                       </li>
                      <?php if(isset($userInfo->storage->id)){
                            if($userInfo->storage->account_type == "admin")
                   echo "   <li>
                          <a href='$url/user/admin-tools' role='button' data-toggle='modal'><i class='glyphicon glyphicon-wrench'></i>Admin Tools</a>  
                      </li>
                      
                      ";
                      }?>
                            
                      <li>
                          <?php if(!isset($userInfo->storage->id))
                 echo"         <a id='modal_trigger' href='#modal'><i class='glyphicon glyphicon-user'>&nbsp&nbsp;</i>Login/SignUp</a>";
			
                          else                  echo"   <a id='modal_trigger' href='$url/user/logout'>SignOut</a>";
                            ?>
                          
                          <div id="modal" class="popupContainer" style="display:none;">
		<header class="popupHeader">
			<span class="header_title" style="color:#666">Login</span>
			<span class="modal_close" onclick="cls();"><i class="fa fa-times"></i></span>
		</header>
		
		<section class="popupBody">
			

			<!-- Username & Password Login form -->
			<div class="user_login">
				<form id="login" style="color:#666" method="POST" action="<?php echo $this->baseUrl();?>/user/login">
                                    
                                    <div id="signincheck" style='color:#C12B05;'></div>
				<label>Username</label>
					<input type="text" id="loginemail" name="username" />
                                        
					<label>Password</label>
					<input type="password" id="loginpassword" name="password"/>
					

					<div class="checkbox">
						<input id="remember" type="checkbox" />
						<label for="remember">Remember me on this computer</label>
					</div>
                                            
                                            
					<div class="action_btns">
                                            <div class="one_half last"><a href="#" id="register_form" class="btn">Sign up</a></div>
                                            <div class="one_half last"><a href="" id="loginform" class="btn btn_red" onclick="return check(this)">Login</a></div>
					</div>
				</form>

				<a href="#" class="forgot_password">Forgot password?</a>
			</div>

			<!-- Register Form -->
			<div class="user_register">
				<form style="color:#666" id="signup" action="<?php echo $this->baseUrl();?>/user/signup" method="POST" >
                                     <div id="signupcheck" style='color:#C12B05;'></div>
					<label>User Name</label>
					<input type="text" name="username" id="signupusername"/>
					<br />

					<label>Email Address</label>
					<input type="email" name="email" id="signupemail"/>
					<br />

					<label>Password</label>
					<input type="password" name="password" id="signuppassword"/>
					<br />


					<div class="action_btns">
                                            <div class="one_half"><a href="#" class="btn back_btn" ><i class="fa fa-angle-double-left"></i> Back</a></div>
						<div class="one_half last"><a href="<?php echo $this->baseUrl();?>/user/signup" id="signupform" class="btn btn_red" onclick="return check(this);">Register</a></div>
					</div>
				</form>
			</div>
		</section>
	</div>



                      </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-cog" style="right:25px"></i></a>
                         <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu" style="right:200px;" >
                             <li class="dropdown-submenu"><a href="<?= $this->baseUrl(); ?>/user/profile">My Profile</a> 
                                 <ul class="dropdown-menu">
                             <li><a href="<?= $this->baseUrl(); ?>/user/addinfo">Add Information</a></li>
                             <li><a href="<?= $this->baseUrl(); ?>/user/editinfo">Edit Profile</a></li>
                             </ul>
                                 </li> 
                             <li><a href="">More</a></li>
                             <li><a href="">More</a></li>
                             <li><a href="">More</a></li>
                         </ul>
                      </li>
                    </ul>   
      
                        </nav> 
                </div> 

                            <!-- old one -->
                 <!--   <ul class="nav navbar-nav navbar-right">
                      <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-cog" style="right:20px"></i></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-submenu"><a href="<?=$this->baseUrl();?>/user/profile">My Profile</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->baseUrl();?>/user/addinfo">Add extra Info</a></li>
                                    <li><a href="<?=$this->baseUrl();?>/user/editinfo">Edit profile</a></li>
                                </ul>
                            </li>
                          <li><a href="">More</a></li>
                          <li><a href="">More</a></li>
                          <li><a href="">More</a></li>
                          <li><a href="">More</a></li>
                        </ul>
                      </li>
                    </ul>   -->
                <!-- /top nav -->
             <?php echo $this->layout()->content; ?>
              
            </div>
              <!-- /main -->
          
        </div>
    </div>
</div>


<!--post modal-->
<div id="postModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			Update Status
      </div>
      <div class="modal-body">
          <form class="form center-block">
            <div class="form-group">
              <textarea class="form-control input-lg" autofocus="" placeholder="What do you want to share?"></textarea>
            </div>
          </form>
      </div>
      <div class="modal-footer">
          <div>
          <button class="btn btn-primary btn-sm" data-dismiss="modal" aria-hidden="true">Post</button>
            <ul class="pull-left list-inline"><li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li><li><a href=""><i class="glyphicon glyphicon-camera"></i></a></li><li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li></ul>
		  </div>	
      </div>
  </div>
  </div>
</div>
        





        
        <!-- JavaScript jQuery code from Bootply.com editor -->
        
        <script type='text/javascript'>
	$("#modal_trigger").leanModal({ closeButton: ".modal_close" });

	$(function(){
		// Calling Login Form
		$("#login_form").click(function(){
			//$(".social_login").hide();
			$(".user_login").show();
			return false;
		});

		// Calling Register Form
		$("#register_form").click(function(){
			$(".user_login").hide();
			$(".user_register").show();
			$(".header_title").text('Register');
			return false;
		});

		// Going back to Social Forms
		$(".back_btn").click(function(){
			$(".user_login").show();
			$(".user_register").hide();
			//$(".social_login").show();
			$(".header_title").text('Login');
			return false;
		});

	});




        
        $(document).ready(function() {
        
            /* off-canvas sidebar toggle */

$('[data-toggle=offcanvas]').click(function() {
  	$(this).toggleClass('visible-xs text-center');
    $(this).find('i').toggleClass('glyphicon-chevron-right glyphicon-chevron-left');
    $('.row-offcanvas').toggleClass('active');
    $('#lg-menu').toggleClass('hidden-xs').toggleClass('visible-xs');
    $('#xs-menu').toggleClass('visible-xs').toggleClass('hidden-xs');
    $('#btnShow').toggle();
});
        
        });
        
        function checkEmail(email) {

    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    if (!filter.test(email)) {
    return false;
    }
    else return true;
        }
 
        
     function check(element){
         
        if(element.id=="signupform"){
            console.log("signup");
         var e= document.getElementById("signupemail").value;
         var u = document.getElementById("signupusername").value;
         var p = document.getElementById("signuppassword").value;
         var div = document.getElementById("signupcheck");
         var form =document.getElementById("signup");
           if(e == null || e == "",u == null || u=="",p == null || p==""){
             
            div.innerHTML="Please Fill all required fields";
           return false; 
     
         }
         else if(!checkEmail(e)){  
           div.innerHTML="Email is inncorrect";
           return false;
         }
       
       else form.submit();
            
            
            
        }
        
        else{    
            console.log("signin");
         var e= document.getElementById("loginemail").value;
         var p = document.getElementById("loginpassword").value;
         var div = document.getElementById("signincheck");
         var form =document.getElementById("login");
            
             if(e == null || e == "",p == null || p==""){
             
            div.innerHTML="Please Fill all required fields";
           return false; 
     
         }
         else {console.log("hiiiii");form.submit();}
            
            
            
            
        }
         
         
      return false;   
     }  ; 
        
       function cls(){
        document.getElementById("signincheck").innerHTML="";   
        document.getElementById("signupcheck").innerHTML="";   
       }; 
        
        </script>
        
    </body>
</html>



