<div class="container" style="margin-top: 100px;">
	<div class="row clearfix">
		<div class="col-md-12 column">
		</div>
	</div>
	<div class="row clearfix">
		<div class="col-md-3 column">
                   
                  <div class="panel panel-default" style="border-color:#DAB4B4; box-shadow: 1px 1px 1px black ;">
				<div class="panel-body" onclick="getUsers()">
                                        Users
				</div>
                      <div class="panel-body" onclick="getCategories();">
					Forum Categories
				</div>
				<div class="panel-body"onclick="getForums();">
					Forums
				</div>  
                                <div class="panel-body" onclick="getThreads();">
					Threads
				</div>  
                                <div class="panel-body">
					Back Home
				</div>  
                  </div>
		</div>
		<div class="col-md-9 column">
                         <div id="notify" style="display:none; margin:10px; width:40%; border:1px solid; border-radius:2px; height:30px; padding:5px;"></div>
                        
			<div class="btn-group">
				 <button class="btn btn-default" type="button"><em class="glyphicon glyphicon-align-left"></em> Left</button> <button class="btn btn-default" type="button"><em class="glyphicon glyphicon-align-center"></em> Center</button> <button class="btn btn-default" type="button"><em class="glyphicon glyphicon-align-right"></em> Right</button> <button class="btn btn-default" type="button"><em class="glyphicon glyphicon-align-justify"></em> Justify</button>
			</div>
			<table id="mytable" class="table table-hover table-bordered">
				
			</table>
		</div>
	</div>
</div>

<script>
    
    $(".panel-body").hover(
  function() {
    $(this).css("background","#2E64FE");$(this).css("color","white");},function(){$(this).css("background","white");$(this).css("color","#555555");});
  
  
    
    $( ".panel-body.fade" ).hover(function() {
  $( this ).fadeOut( 100 );
  $( this ).fadeIn( 500 );
});
    
    
    function getUsers(){
        
        var table=document.getElementById("mytable");
        table.innerHTML="<thead><tr><th>#</th><th>Email</th><th>Username</th><th>status</th><th>Action</th></tr></thead><tbody id='tablebody'></tbody>";
	var body = document.getElementById("tablebody");	
        $.getJSON("/ZendProject/public/user/userajax/read/1",function(data,status){
        var content="";
        var st="";
	console.log(data);
        for(var i in data ){
            if(data[i].status == "banned") st="danger";
            else if(data[i].status == "online") st="success";
                else st="";
       content+="<tr class='"+st+"'><td>"+data[i].id+"</td><td>"+data[i].email+"</td><td>"+data[i].username+"</td><td>"+data[i].status+
               "</td><td><i class='glyphicon glyphicon-info-sign' title='View Profile'></i>&nbsp&nbsp<i class='glyphicon glyphicon-pencil' title='Edit' onclick=\"goEdit("+data[i].id+");\"></i>&nbsp&nbsp<i class='glyphicon glyphicon-trash' title='Delete User' onclick=\"goDel("+data[i].id+");\"></i>&nbsp&nbsp"+
             "<i class='glyphicon glyphicon-ban-circle' title='Ban User'></i>&nbsp&nbsp";          
            
     
        }
        
        body.innerHTML=content+"</tbody>";
        
        
    });
    
    
    }
    
    
    
    function getThreads(){
    
    
      var table=document.getElementById("mytable");
        table.innerHTML="<thead><tr><th>#</th><th>Name</th><th>Forums/Threads</th><th>Action</th></tr></thead><tbody id='tablebody'></tbody>";
	var body = document.getElementById("tablebody");	
    $.getJSON("/ZendProject/public/user/categoryajax/read/1",function(data,status){
        var content="";
        for(var i in data ){
       content+="<tr id='"+data[i].id+"'><td><i class='glyphicon glyphicon-list-alt' title='Forum'></i><a href='#'>"+data[i].name+"</a><br>"+data[i].description+"</td><td>"+data[i].threads+"</td><td>"+data[i].posts+"</td></tr>";          
        }
        
        body.innerHTML=content+"</tbody>";
        
        
    });
    
    
    
    }
    
    function notification(message,color){
    
     var notify = document.getElementById("notify");
            notify.style.display="block";
            notify.style.background = color;
            notify.innerHTML=message;
            setTimeout(function(){ notify.style.display="none";},6000);
    
    
    }
    
    function goDel(id){
    
        $.get("/ZendProject/public/user/userajax/delete/"+id,function(status){
            
           if(status != 400 && status != 404){
               
           notification("User Successfully Deleted","#57E964");
               
            }
            
            else notification("Failed To Delete User Try Again Later","#F75D59");
            
            
        });
        getUsers();
    }
    
    
    
    
    
    
    
    
    
 </script>   
