
	<div class="row clearfix" style="margin-top: 100px;">
		<div class="col-md-12 column">
		</div>
	</div>
	<div class="row clearfix">
		<div class="col-md-3 column">
                   
                  <div class="panel panel-default" style="border-color:#DAB4B4; box-shadow: 1px 1px 1px black ;">
				<div class="panel-body" onclick="getUsers()">
                                        List Users
				</div>
                      <div class="panel-body" onclick="addCat();">
					Add Category
				</div>
				<div class="panel-body"onclick="addForum();">
					Add Forum
				</div>  
                                <div class="panel-body" onclick="getThreads();">
					Administrative browsing 
				</div> 
                                <div class="panel-body" onclick="lockSystem();">
					Lock System 
				</div>                                 
                               
                  </div>
		</div>
		<div class="col-md-9 column">
                         <div id="notify" style="display:none; margin:10px; width:40%; border:1px solid; border-radius:2px; height:30px; padding:5px;"></div>
                        
			
                         <div class="checkbox" id="lock" style="display:none; margin:10px; width:200px; height:40px; padding:5px;">
                             <label style="font-size: 18px; text-align:center;"><input type="checkbox" id="checkBox" onchange="getCheckBoxValue();"/> Lock the entire system </label>
                         </div>
			<table id="mytable" class="table table-hover table-bordered">
				
			</table>
		</div>
	</div>
   


<script>
    console.log( <?= $this->check?>);
    
    $(".panel-body").hover(
  function() {
    $(this).css("background","#2E64FE");$(this).css("color","white");},function(){$(this).css("background","white");$(this).css("color","#555555");});
  
  
    
    $( ".panel-body.fade" ).hover(function() {
  $( this ).fadeOut( 100 );
  $( this ).fadeIn( 500 );
});
    
    
    function getUsers(){
        
        var table=document.getElementById("mytable");
        table.innerHTML="<thead><tr><th>#</th><th>Email</th><th>Username</th><th>status</th><th>Account type</th><th>Action</th></tr></thead><tbody id='tablebody'></tbody>";
	var body = document.getElementById("tablebody");	
        $.getJSON("/ZendProject/public/user/userajax/read/1",function(data,status){
        var content="";
        var st="";
	console.log(data);
        var title="ban";
        var acc="admin";
        for(var i in data ){
            if(data[i].status == "banned"){ st="danger";title="unban"; }
            else if(data[i].status == "online") st="success";
            else st="";
            
            if(data[i].account_type == "admin") acc="normal";
            
       content+="<tr class='"+st+"'><td>"+data[i].id+"</td><td>"+data[i].email+"</td><td>"+data[i].username+"</td><td>"+data[i].status+
               "</td><td>"+data[i].account_type+"</td><td><i class='glyphicon glyphicon-info-sign' title='View Profile' onclick=\"viewprofile("+data[i].id+")\"></i>&nbsp&nbsp<i class='glyphicon glyphicon-pencil' title='Edit' onclick=\"goEdit("+data[i].id+");\"></i>&nbsp&nbsp<i class='glyphicon glyphicon-trash' title='Delete User' onclick=\"goDel("+data[i].id+");\"></i>&nbsp&nbsp"+
             "<i class='glyphicon glyphicon-ban-circle' title='"+title+"' onclick=\"ban('"+title+"',"+data[i].id+")\"></i>&nbsp&nbsp<i class='glyphicon glyphicon-bookmark' title='change account to "+acc+"' onclick=\"account_type('"+acc+"',"+data[i].id+")\"></i>";          
            
            title="ban";
            st="";
            acc="admin";
        }
        
        body.innerHTML=content+"</tbody>";
        
        
    });
    
    
    }
    
    function addCat(){
    
     window.location.href="/ZendProject/public/category/add";
     
    }
    
    function addForum(){
    
     window.location.href="/ZendProject/public/forum/add";
     
    }
    
    
    function getThreads(){
    
       window.location.href='/ZendProject/public/category/ajax-job';
    
    }
    
    function lockSystem(){
    
       var lockCheck = document.getElementById("lock");
       lockCheck.style.display="block";
    }
    function  getCheckBoxValue(){
       var checkBox = document.getElementById("checkBox");
       if(checkBox.checked){
           //alert("true");
             $.get("/ZendProject/public/user/userajax/lock/true",function(data,status){
            console.log(data);
           if(status != 400 && status != 404){
               
           notification("System Locked","#57E964");
           
               
            }
            
            else notification("Failed To Lock System","#F75D59");
            
            
        });
       }else{
           //alert("false");
         $.get("/ZendProject/public/user/userajax/lock/false",function(data,status){
            console.log(data);
           if(status != 400 && status != 404){
               
           notification("System UnLocked","#57E964");
           
               
            }
            
            else notification("Failed To UnLock System","#F75D59");
            
            
        });
       }
    }
    
    function notification(message,color){
    
     var notify = document.getElementById("notify");
            notify.style.display="block";
            notify.style.background = color;
            notify.innerHTML=message;
            setTimeout(function(){ notify.style.display="none";},6000);
    
    
    }
    
    function goDel(id){
    
        $.get("/ZendProject/public/user/userajax/delete/"+id,function(status){
            
           if(status != 400 && status != 404){
               
           notification("User Successfully Deleted","#57E964");
           getUsers();
               
            }
            
            else notification("Failed To Delete User Try Again Later","#F75D59");
            
            
        });
        
    }
    
    
    function account_type(change,id){
        console.log(change+"    "+id);
        $.get("/ZendProject/public/user/userajax/account_type/"+change+"/Id/"+id,function(data,status){
            console.log("response");
           if(data > 0){
               
           notification("User account type changed to "+change,"#57E964");
           getUsers();
               
            }
            
            else notification("Couldn't user account type","#F75D59");
            
            
        });
        
    }
    
    
    function ban(action,id){
    
        $.get("/ZendProject/public/user/userajax/"+action+"/"+id,function(status){
            
           if(status != 400 && status != 404 && status !=500){
               
           notification("User Successfully "+action+"ed","#57E964");
            getUsers();
               
            }
            
            else notification("Failed To Ban User Try Again Later","#F75D59");
            
            
        });
       
    }
    
    function viewprofile(id){
    
        window.location.href="/ZendProject/public/user/profile/userId/"+id;
            
       
    }
    
    function goEdit(id){
    
        window.location.href="/ZendProject/public/user/editinfo/userId/"+id;
            
    
    }
    
    
    
    
    
    
    
    
    
    
 </script>   
