<br /><br />
<div id="view-content">
    <?php if (isset($this->error)){
               
                if($this->error == 'login'){
            echo "<script> 
                window.onload=function (){document.getElementById('signincheck').innerHTML='Incorrect Username or Password';
                           
                            document.getElementById('modal_trigger').click();}
                            </script>";
                }
                
           
                
                
                 else if($this->error == 'signup'){
                    echo "<script> 
                        window.onload=function (){document.getElementById('signupcheck').innerHTML='Email Or Username Already Exists';
                            document.getElementById('register_form').click();
                            document.getElementById('modal_trigger').click();}
                            </script>";
                  
                }
                

                
                    }
    
    echo $this->lock["status"]; 
    echo $this->id;
    echo $this->acc;
    echo $this->status;
    $userInfo = new Zend_Session_Namespace('Zend_Auth');
    echo $userInfo->storage->id;
    echo $userInfo->storage->account_type;
    echo $userInfo->storage->status;
echo $this->error;
echo $this->id2;
echo strcmp($this->status, 'banned')."hiiiiiiiiiiiiiii";
if(strcmp($this->status,"banned")== 0){

            echo "<script> 
                window.onload=function (){document.getElementById('signincheck').innerHTML='User banned';
                           
                            document.getElementById('modal_trigger').click();}
                            </script>";            
                    }
    
              
      ?>

    
</div>