<style>
    .label{
        font-weight:bold;
        color: black;
        font-size: 20px;
    }
    .value{
        color: #686868 ;
        font-size: 18px;
    }
</style>
<div class="container" style='margin-top:100px;'>
    <div class="row clearfix">
	<div style="border: 1px solid #484848 ; border-radius:25px; width: 900px; height: 600px; padding-top:50px; padding-left: 25px;" >	
        <div class="col-md-3 column">
                    <img alt="140x140" src="<?php echo $this->baseUrl().$this->userData["image"]; ?>" height="200px" width="200px" />
                </div>
                <div class="col-md-4 column" style='margin-top:150px;'>
                    <label class="label">First name : </label><label class="value"><?= $this->userData["fname"]; ?></label><br><br>
                    <label class="label">Last name : </label><label class="value"><?= $this->userData["lname"]; ?></label><br><br>
                    <label class="label">Username : </label><label class="value"><?= $this->userData["username"]; ?></label><br><br>
                    <label class="label">Gender : </label><label class="value"><?php
                        if ($this->userData["gender"] == 'f') {
                            echo "Female";
                        } elseif ($this->userData["gender"] == 'm') {
                            echo "Male";
                        }
                        ?></label><br><br>
                    <label class="label">E-mail : </label><label class="value"><?= $this->userData["email"]; ?></label><br><br>
                </div>

        </div>
        </div>
  <!--  <a href="<?php //echo $this->baseUrl();?>/user/editinfo" style=" color: blue; position: absolute; top: 100px; left:800px;">Edit profile info</a> -->
</div>
                       